### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by wang-qitong** [zixuzhuang/CSNet#3]
你好，我想问一下 “-grade <grade> -graph <graph-save-path> -mesh <mesh-save-path> <fold-idx> <test-mode>”这里面的几个参数应该怎么填呢，谢谢！

**Comment by zixuzhuang** [comment]
In graph_construction.py, you will find:

    parser = argparse.ArgumentParser(description="Graph Representation")
    parser.add_argument("-org", type=str, default="data/MRI/org.nii.gz", help="MRI file")
    parser.add_argument("-seg", type=str, default="data/MRI/seg.nii.gz", help="segmentation file")
    parser.add_argument("-grade", type=int, default=0, help="cartilage defect grade, default: 0")
    parser.add_argument("-graph", type=str, default="data/knee_graph/example_0.npz", help="save path of knee graph")
    parser.add_argument("-mesh", type=str, default="data/knee_mesh/example_0.npz", help="save path of knee mesh for visualization")
    args = parser.parse_args()
